
arch:
  - arm64

env:
  - IMGNAME=metacringer/web:js

services:
  - docker

before_install:
- docker build -t ${IMGNAME}

after_success:
- docker login -u ${DHUB_USERNAME} -p ${DHUB_PASSWORD}
- docker push ${IMGNAME}